/**
 * SQL Hero Challenge Processing Module
 * 
 * This module handles the processing of SQL challenges, including markdown parsing,
 * code highlighting, and constants generation. It provides utilities for file checking,
 * frontmatter processing, and challenge data management.
 * 
 * @module sql-hero/challenge-processor
 */

import fs from 'fs/promises';
import matter from 'gray-matter';
import { marked } from 'marked';
import { JSDOM } from "jsdom";
import hljs from "highlight.js";
import { ShortChallenge } from '../src/lib/types';

const ER_DIAGRAMS = new Set<string>();

/**
 * Interface for Vite plugin configuration
 */
export interface VitePlugin {
    /** Name of the Vite plugin */
    name: string;

    /**
     * Resolves the ID of a source file
     * @param source - Source file path
     * @returns Resolved ID or null if not handled
     */
    resolveId(source: string): string | null;

    /**
     * Loads the content of a file
     * @param id - File identifier
     * @returns Promise resolving to the file content
     */
    load(id: string): Promise<string | undefined>;
}

/**
 * Represents a SQL challenge with its properties
 */
interface Challenge {
    /** Sequential number of the challenge */
    number: number;

    /** Title of the challenge */
    title: string;

    /** Detailed description of the challenge */
    description: string;

    /** Difficulty level of the challenge */
    difficulty: 'easy' | 'medium' | 'hard';

    /** SQL query for the challenge */
    query: string;

    /** Hashed result for verification */
    hashedResult: string;

    /** Array of hints to help solve the challenge */
    hints: string[];

    /** Schema file name */
    schema: string;

    /** ERD file name */
    erd?: string;
}

/**
 * Checks if a file or directory exists at the specified path
 * @param filePath - Path to check for existence
 * @returns Promise resolving to true if the path exists, false otherwise
 * @throws Never throws, returns false on any file system error
 */
const isExisting: (filePath: string) => Promise<boolean> = async (
    filePath: string
): Promise<boolean> => {
    try {
        await fs.stat(filePath);
        return true;
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
    } catch (_) {
        return false;
    }
};

/**
 * Processes markdown frontmatter and content
 * @param markdown - Raw markdown content with frontmatter
 * @returns Promise resolving to an object containing parsed frontmatter data and HTML markup
 */
async function processFrontmatter(markdown: string) {
    const { data, content } = matter(markdown);
    const markup = await marked(content);
    return {
        data,
        markup,
    };
}

/**
 * Applies syntax highlighting to code blocks in HTML markup
 * @param markup - HTML markup containing code blocks
 * @returns Serialized HTML with highlighted code blocks
 */
function highlightCode(markup: string) {
    const dom = new JSDOM(markup);
    const codeBlocks = dom.window.document.querySelectorAll('pre code');
    for (const block of codeBlocks) {
        hljs.highlightElement(block as HTMLElement);
    }

    return dom.window.document.querySelector('body')?.innerHTML ?? '';
}

/**
 * Generates TypeScript constants file containing challenge data
 * @param options - Object containing challenges array and total count
 * @param options.challenges - Array of challenge objects
 * @param options.count - Total number of challenges
 * @returns Promise resolving to generated TypeScript code as string
 */
async function generateConstants({
    challenges,
    count
}: {
    challenges: ShortChallenge[];
    count: number;
}) {
    const erds = Array.from(ER_DIAGRAMS);
    const len = erds.length;
    let code = `/**
* Application constants
* Generated by sql-hero plugin
* DO NOT MODIFY
*/
export const APP_NAME = 'SQL Hero';
export const COUNT_CHALLENGES = ${count};
export const CHALLENGES = [\n`;

    challenges.sort((a, b) => a.number - b.number);
    for (const challenge of challenges) {
        code += JSON.stringify(challenge, null, 4);
        code += ',\n';
    }

    code += '];\n';

    for (let i = 0; i < len; i++) {
        const erd = erds[i];
        code += `export const ER_DIAGRAM_${i} = '${erd}';\n`;
    }

    return code;
}

/**
 * Creates a Vite plugin that processes SQL challenges from markdown files
 * and generates necessary application constants and challenge files.
 * 
 * The plugin performs the following tasks:
 * 1. Reads markdown files from the specified input path
 * 2. Processes frontmatter and content
 * 3. Generates JSON files for each challenge
 * 4. Creates a virtual module with challenge constants
 * 
 * @param options - Plugin configuration options
 * @param options.path - Directory path containing challenge markdown files
 * @param options.output - Output directory path for processed challenge files
 * @returns VitePlugin instance for processing SQL challenges
 * 
 * @example
 * ```ts
 * // vite.config.ts
 * import createChallenges from './plugins/create-challenges';
 * 
 * export default defineConfig({
 *   plugins: [
 *     createChallenges({
 *       path: './challenges',
 *       output: './dist/challenges'
 *     })
 *   ]
 * });
 * ```
 */
export default function createChallenges({ path, output }: {
    path: string;
    output: string;
}): VitePlugin {
    const virtualModuleId = 'virtual:sql-hero';
    const resolvedVirtualModuleId = '\0' + virtualModuleId;

    return {
        name: 'create-challenges',
        resolveId(id) {
            if (id === virtualModuleId) {
                return resolvedVirtualModuleId
            }

            return null;
        },
        async load(id: string): Promise<string | undefined> {
            if (id === resolvedVirtualModuleId) {
                let index = 0;
                // let lastSchema = '';
                const files = await fs.readdir(path);
                const challenges: ShortChallenge[] = new Array(files.length);
                // const erds = new Set<string>();

                if (!await isExisting(output)) {
                    await fs.mkdir(output, { recursive: true });
                }

                for (const file of files) {
                    const content = await fs.readFile(`${path}/${file}`, 'utf-8');
                    const { data, markup } = await processFrontmatter(content);
                    const challenge: Challenge = {
                        ...data as Challenge,
                        description: highlightCode(markup),
                    }

                    challenges[index++] = {
                        number: challenge.number,
                        title: challenge.title,
                        difficulty: challenge.difficulty,
                        schema: challenge.schema,
                    };

                    fs.writeFile(`${output}/${file.replace('.md', '.json')}`, JSON.stringify(challenge).replace(/\\\\/g, '\\'));
                }

                return (await generateConstants({ challenges, count: files.length }));
            }
        }
    };
}