import { InputOptions } from 'rollup';
/**
 * Vite/Rollup plugin to count challenges and generate constants
 * ToDo: Consider renaming to `generateConstants`
 */
import fs from 'node:fs/promises';

export interface VitePlugin {
    name: string;
    // buildStart(): Promise<void>;
    options(opt: InputOptions): Promise<InputOptions>;
    // resolveId(source: string): string | null;
    // load(id: string): Promise<string | null>;
}

async function generateConstants(path: string) {
    
    const files = await fs.readdir(path);
    const count = files.length;
    const challenges: Array<{no: number, title: string}> = [];
    let code = `/**
* Application constants
* Generated by count-challenges plugin
* DO NOT MODIFY
*/
export const APP_NAME = 'SQL Hero';
export const COUNT_CHALLENGES = ${count};
export const CHALLENGES = `;

    for (const file of files) {
        const content = await fs.readFile(`${path}/${file}`, 'utf-8');
        const json = JSON.parse(content);
        challenges.push({                
            no: json.no,
            title: json.title,
        });
    }

    code += JSON.stringify(challenges.sort((a, b) => a.no - b.no), null, 4);
    code += ';\n';

    return code;
}

/**
 * Vite/Rollup plugin to count challenges and generate constants
 * 
 * @description
 * A build plugin that:
 * - Counts files in a specified directory
 * - Generates a constants file with application name and challenge count
 * - Runs at build start
 * 
 * @param {string} path - Directory path to count files from
 * @returns {Object} Plugin object with buildStart hook
 * 
 * @example
 * ```ts
 * // vite.config.ts
 * import countChallenges from './plugins/countChallenges';
 * 
 * export default defineConfig({
 *   plugins: [
 *     countChallenges('./challenges')
 *   ]
 * });
 * ```
 */
export default function countChallenges(path: string): VitePlugin {
    return {
        name: 'vite-count-challenges',
        // async buildStart() {
        //     const filePath = 'src/constants.ts';
        //     const code = await generateConstants(path);
        //     fs.writeFile(filePath, code);
        // },
        async options(opts) {
            const filePath = 'src/constants.ts';
            const code = await generateConstants(path);
            fs.writeFile(filePath, code);
            return opts;
        }
        // resolveId(source) {
        //     if (source === 'virtual-module') {
        //         return source;
        //     }

        //     return null;
        // },
        // async load(id) {
        //     if (id === 'virtual-module') {
        //         return generateConstants(path);
        //     }

        //     return null;
        // }
    };   
}