import fs from 'node:fs/promises';

export interface VitePlugin {
    name: string;
    buildStart(): Promise<void>;
}

/**
 * Vite/Rollup plugin to count challenges and generate constants
 * 
 * @description
 * A build plugin that:
 * - Counts files in a specified directory
 * - Generates a constants file with application name and challenge count
 * - Runs at build start
 * 
 * @param {string} path - Directory path to count files from
 * @returns {Object} Plugin object with buildStart hook
 * 
 * @example
 * ```ts
 * // vite.config.ts
 * import countChallenges from './plugins/countChallenges';
 * 
 * export default defineConfig({
 *   plugins: [
 *     countChallenges('./challenges')
 *   ]
 * });
 * ```
 */
export default function countChallenges(path: string): VitePlugin {
    const filePath = 'src/constants.ts';
    return {
        name: 'vite-count-challenges',
        async buildStart() {
            const files = await fs.readdir(path);
            const count = files.length;
            const code = `/**
 * Application constants
 * Generated by count-challenges plugin
 * DO NOT MODIFY
 */
export const APP_NAME = 'SQL Hero';
export const COUNT_CHALLENGES = ${count};
`;
            await fs.writeFile(filePath, code);
        }
    }
}