/**
 * SQL Hero Challenge Processing Module
 * 
 * This module handles the processing of SQL challenges, including markdown parsing,
 * code highlighting, and constants generation. It provides utilities for file checking,
 * frontmatter processing, and challenge data management.
 * 
 * @module sql-hero/challenge-processor
 */

import fs from 'fs/promises';
import matter from 'gray-matter';
import { marked } from 'marked';
import { JSDOM } from "jsdom";
import hljs from "highlight.js";
import { ShortChallenge } from '../src/lib/types';

/**
 * Interface for Vite plugin configuration
 */
export interface VitePlugin {
    /** Name of the Vite plugin */
    name: string;

    /**
     * Resolves the ID of a source file
     * @param source - Source file path
     * @returns Resolved ID or null if not handled
     */
    resolveId(source: string): string | null;

    /**
     * Loads the content of a file
     * @param id - File identifier
     * @returns Promise resolving to the file content
     */
    load(id: string): Promise<string | undefined>;
}

/**
 * Checks if a file or directory exists at the specified path
 * @param filePath - Path to check for existence
 * @returns Promise resolving to true if the path exists, false otherwise
 * @throws Never throws, returns false on any file system error
 */
const isExisting: (filePath: string) => Promise<boolean> = async (
    filePath: string
): Promise<boolean> => {
    try {
        await fs.stat(filePath);
        return true;
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
    } catch (_) {
        return false;
    }
};

/**
 * Processes markdown frontmatter and content
 * @param markdown - Raw markdown content with frontmatter
 * @returns Promise resolving to an object containing parsed frontmatter data and HTML markup
 */
async function processFrontmatter(markdown: string) {
    const { data, content } = matter(markdown);
    const markup = await marked(content);
    return {
        data,
        markup,
    };
}

/**
 * Applies syntax highlighting to code blocks in HTML markup
 * @param markup - HTML markup containing code blocks
 * @returns Serialized HTML with highlighted code blocks
 */
function highlightCode(markup: string) {
    const dom = new JSDOM(markup);
    const codeBlocks = dom.window.document.querySelectorAll('pre code');
    for (const block of codeBlocks) {
        hljs.highlightElement(block as HTMLElement);
    }

    return dom.window.document.querySelector('body')?.innerHTML ?? '';
}

/**
 * Generates TypeScript constants file containing challenge data
 * @param options - Object containing challenges array and total count
 * @param options.challenges - Array of challenge objects
 * @param options.count - Total number of challenges
 * @returns Promise resolving to generated TypeScript code as string
 */
async function generateConstants({
    breakpoints = [['sm', 640], ['md', 768], ['lg', 1024], ['xl', 1280]],
    challenges,
    count
}: {
    breakpoints?: [string, number][];
    challenges: ShortChallenge[];
    count: number;
}) {
    challenges.sort((a, b) => a.number - b.number);

    let code = `/**
* Application constants
* Generated by sql-hero plugin
* DO NOT MODIFY
*/
export const APP_NAME = 'SQL Hero';
export const COUNT_CHALLENGES = ${count};\n
export const BREAKPOINTS = {\n`;

    for (const [name, width] of breakpoints) {
        code += `    '${name}': ${width},\n`;
    }

    code += '};\n';
    code += `
export const CHALLENGES = [\n`;

    for (const challenge of challenges) {
        code += JSON.stringify(challenge, null, 4);
        code += ',\n';
    }

    code += '];\n';

    return code;
}

/**
 * Creates a Vite plugin that processes SQL challenges from markdown files
 * and generates necessary application constants and challenge files.
 * 
 * The plugin performs the following tasks:
 * 1. Reads markdown files from the specified input path
 * 2. Processes frontmatter and content
 * 3. Generates JSON files for each challenge
 * 4. Creates a virtual module with challenge constants
 * 
 * @param options - Plugin configuration options
 * @param options.path - Directory path containing challenge markdown files
 * @param options.output - Output directory path for processed challenge files
 * @returns VitePlugin instance for processing SQL challenges
 * 
 * @example
 * ```ts
 * // vite.config.ts
 * import createChallenges from './plugins/create-challenges';
 * 
 * export default defineConfig({
 *   plugins: [
 *     createChallenges({
 *       path: './challenges',
 *       output: './dist/challenges'
 *     })
 *   ]
 * });
 * ```
 */
export default function createChallenges({ path, output, breakpoints }: {
    path: string;
    output: string;
    breakpoints?: [string, number][];
}): VitePlugin {
    const virtualModuleId = 'virtual:sql-hero';
    const resolvedVirtualModuleId = '\0' + virtualModuleId;

    return {
        name: 'create-challenges',
        resolveId(id) {
            if (id === virtualModuleId) {
                return resolvedVirtualModuleId
            }

            return null;
        },
        async load(id: string): Promise<string | undefined> {
            if (id === resolvedVirtualModuleId) {
                let index = 0;
                const files = await fs.readdir(path);
                const challenges: ShortChallenge[] = new Array(files.length);

                if (!await isExisting(output)) {
                    await fs.mkdir(output, { recursive: true });
                }

                for (const file of files) {
                    const content = await fs.readFile(`${path}/${file}`, 'utf-8');
                    const { data, markup } = await processFrontmatter(content);
                    data.description = highlightCode(markup);

                    challenges[index++] = {
                        number: data.number,
                        title: data.title,
                        difficulty: data.difficulty,
                        schema: data.schema,
                    };

                    fs.writeFile(
                        `${output}/${file.replace('.md', '.json')}`, 
                        JSON.stringify(data).replace(/\\\\/g, '\\')
                    );
                }

                return (await generateConstants({ 
                    breakpoints, 
                    challenges, 
                    count: files.length,
                }));
            }
        }
    };
}