/**
 * Application constants
 * Generated by count-challenges plugin
 * DO NOT MODIFY
 */
export const APP_NAME = 'SQL Hero';
export const COUNT_CHALLENGES = 81;
export const CHALLENGES = [
    {
        "no": 1,
        "title": "Woher kommen die Kunden?"
    },
    {
        "no": 2,
        "title": "Anzahl Länder"
    },
    {
        "no": 3,
        "title": "Woher kommen die MEISTEN Kunden?"
    },
    {
        "no": 4,
        "title": "Name Mitarbeiter"
    },
    {
        "no": 5,
        "title": "Empfänger / Where-Klausel?"
    },
    {
        "no": 6,
        "title": "Bestellte Artikel"
    },
    {
        "no": 7,
        "title": "Kundentelefonliste"
    },
    {
        "no": 8,
        "title": "Geburtstagsliste"
    },
    {
        "no": 9,
        "title": "Artikel der Firma"
    },
    {
        "no": 10,
        "title": "Betreute Kunden"
    },
    {
        "no": 11,
        "title": "Bestellte Artikel von Firma"
    },
    {
        "no": 12,
        "title": "Preiserhöhung"
    },
    {
        "no": 13,
        "title": "Anzahl bestellte Artikel"
    },
    {
        "no": 14,
        "title": "Anzahl bestellte Getränke"
    },
    {
        "no": 15,
        "title": "Stückzahlen bestellter Artikel"
    },
    {
        "no": 16,
        "title": "Lagerbestand bestimmter Artikel"
    },
    {
        "no": 17,
        "title": "Bestellungen pro Mitarbeiter"
    },
    {
        "no": 18,
        "title": "Gesamtumsatz je Artikel"
    },
    {
        "no": 19,
        "title": "Umsatz pro Auslaufartikel"
    },
    {
        "no": 20,
        "title": "Lagerbestand je Kategorie"
    },
    {
        "no": 21,
        "title": "Anzahl der Kunden 1"
    },
    {
        "no": 22,
        "title": "Anzahl der Kunden 2"
    },
    {
        "no": 23,
        "title": "Teuerste Produkte"
    },
    {
        "no": 24,
        "title": "Bestellungen"
    },
    {
        "no": 25,
        "title": "Bestimmte Kunden 1"
    },
    {
        "no": 26,
        "title": "a-Kunden"
    },
    {
        "no": 27,
        "title": "Bestimmte Kunden 2"
    },
    {
        "no": 28,
        "title": "Bestellungen von „Lakkalikööri“"
    },
    {
        "no": 29,
        "title": "Gesamtumsatz der Mitarbeiter"
    },
    {
        "no": 30,
        "title": "Umsatz der Auslaufartikel"
    },
    {
        "no": 31,
        "title": "Gelieferte Artikel"
    },
    {
        "no": 32,
        "title": "Summe Lagerbestand"
    },
    {
        "no": 33,
        "title": "Mitarbeiter von „Abteilungsleitung“"
    },
    {
        "no": 34,
        "title": "Mitarbeiter von „Controlling“"
    },
    {
        "no": 35,
        "title": "Mitarbeiter Where-Klausel"
    },
    {
        "no": 36,
        "title": "Mitarbeiter von „Controlling“"
    },
    {
        "no": 37,
        "title": "Durchschnittsgehalt pro Abteilung"
    },
    {
        "no": 38,
        "title": "Parteien mit Wähler 1"
    },
    {
        "no": 39,
        "title": "Parteien mit Wähler 2"
    },
    {
        "no": 40,
        "title": "Parteien 1"
    },
    {
        "no": 41,
        "title": "Parteien 2"
    },
    {
        "no": 42,
        "title": "Liste von Schülern"
    },
    {
        "no": 43,
        "title": "Liste von Räumen"
    },
    {
        "no": 44,
        "title": "Liste von Etagen"
    },
    {
        "no": 45,
        "title": "Schüleranzahl"
    },
    {
        "no": 46,
        "title": "Stundenanzahl"
    },
    {
        "no": 47,
        "title": "Stundenanzahl Sport"
    },
    {
        "no": 48,
        "title": "Plätze im Raum 1"
    },
    {
        "no": 49,
        "title": "Plätze im Raum 2"
    },
    {
        "no": 50,
        "title": "Räume in der Etage"
    },
    {
        "no": 51,
        "title": "Plätze in der Etage"
    },
    {
        "no": 52,
        "title": "Unterrichtsfächer"
    },
    {
        "no": 53,
        "title": "Schüler in der Klasse"
    },
    {
        "no": 54,
        "title": "Liste Klasse"
    },
    {
        "no": 55,
        "title": "Liste Unterrichtsfächer"
    },
    {
        "no": 56,
        "title": "Unterrichtsräume 8b"
    },
    {
        "no": 57,
        "title": "Schüler von Raum R112"
    },
    {
        "no": 58,
        "title": "Liste von Klassen und Anzahl Schülern"
    },
    {
        "no": 59,
        "title": "Unterrichtsstunden der Klassen"
    },
    {
        "no": 60,
        "title": "Meiste Unterrichtsstunden"
    },
    {
        "no": 61,
        "title": "Liste Lehrer mir Raum u. Unterrichtsstunden"
    },
    {
        "no": 62,
        "title": "Lehrer- und Schülernamen"
    },
    {
        "no": 63,
        "title": "Disziplinarkonferenz"
    },
    {
        "no": 64,
        "title": "Kein Sportunterricht"
    },
    {
        "no": 65,
        "title": "Klassenkameraden"
    },
    {
        "no": 66,
        "title": "Liste aller Schüler mit Klasse"
    },
    {
        "no": 67,
        "title": "Liste aller Schüler mit Unterricht"
    },
    {
        "no": 68,
        "title": "Schüler ohne Klasse"
    },
    {
        "no": 69,
        "title": "Schüler aus bestimmter Klasse"
    },
    {
        "no": 70,
        "title": "Fachlehrer"
    },
    {
        "no": 71,
        "title": "Klassen mit Fächern"
    },
    {
        "no": 72,
        "title": "Durschnittliche Unterrichtsstunden"
    },
    {
        "no": 73,
        "title": "Unterrichtsfächer und -stunden"
    },
    {
        "no": 74,
        "title": "Klassen in Raum"
    },
    {
        "no": 75,
        "title": "AGs"
    },
    {
        "no": 76,
        "title": "Räume mit Deutschunterricht 1"
    },
    {
        "no": 77,
        "title": "Fachkollegen"
    },
    {
        "no": 78,
        "title": "AGs und Schüler 1"
    },
    {
        "no": 79,
        "title": "AGs und Schüler 2"
    },
    {
        "no": 80,
        "title": "Arbeitsstunden der Lehrer"
    },
    {
        "no": 81,
        "title": "Räume mit Deutschunterricht 2"
    }
];
