/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChallengesNameImport } from './routes/challenges.$name'

// Create Virtual Routes

const OverviewLazyImport = createFileRoute('/overview')()
const IntroductionLazyImport = createFileRoute('/introduction')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const OverviewLazyRoute = OverviewLazyImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/overview.lazy').then((d) => d.Route))

const IntroductionLazyRoute = IntroductionLazyImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/introduction.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ChallengesNameRoute = ChallengesNameImport.update({
  id: '/challenges/$name',
  path: '/challenges/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/introduction': {
      id: '/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionLazyImport
      parentRoute: typeof rootRoute
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewLazyImport
      parentRoute: typeof rootRoute
    }
    '/challenges/$name': {
      id: '/challenges/$name'
      path: '/challenges/$name'
      fullPath: '/challenges/$name'
      preLoaderRoute: typeof ChallengesNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/introduction': typeof IntroductionLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/challenges/$name': typeof ChallengesNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/introduction': typeof IntroductionLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/challenges/$name': typeof ChallengesNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/introduction': typeof IntroductionLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/challenges/$name': typeof ChallengesNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/introduction'
    | '/overview'
    | '/challenges/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/introduction' | '/overview' | '/challenges/$name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/introduction'
    | '/overview'
    | '/challenges/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  IntroductionLazyRoute: typeof IntroductionLazyRoute
  OverviewLazyRoute: typeof OverviewLazyRoute
  ChallengesNameRoute: typeof ChallengesNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  IntroductionLazyRoute: IntroductionLazyRoute,
  OverviewLazyRoute: OverviewLazyRoute,
  ChallengesNameRoute: ChallengesNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/introduction",
        "/overview",
        "/challenges/$name"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/introduction": {
      "filePath": "introduction.lazy.tsx"
    },
    "/overview": {
      "filePath": "overview.lazy.tsx"
    },
    "/challenges/$name": {
      "filePath": "challenges.$name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
