/// <reference types="vite/client" />

/**
 * Virtual module declaration for SQL Hero challenges.
 * This module provides access to the challenges data generated by the Vite plugin.
 */
declare module 'virtual:sql-hero' {
    export const K: string;
    export const APP_NAME: string;
    export const BASE_PATH: string;
    export const COUNT_CHALLENGES: number;
    export const CHALLENGES: ShortChallenge[];
    export const BREAKPOINTS: Record<string, number>;
    export function xorDecode(data: string, key: string): string;
}