/// <reference types="vite/client" />

/**
 * Virtual module declaration for SQL Hero challenges.
 * This module provides access to the challenges data generated by the Vite plugin.
 */
declare module 'virtual:sql-hero' {
    export const APP_NAME: string;
    export const COUNT_CHALLENGES: number;
    export const CHALLENGES: ShortChallenge[];
}